---
- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes

- name: Restart Node Exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes

